[variant] Add Generic F7xx
fpistm/Arduino_Core_STM32 pull request #8
Opened 2021-03-17 09:58 UTC by ABOSTM

**Summary**
[variant] Add Generic F7xx

Fixes #1302

2021-03-17 10:11 UTC, fpistm requested changes

2021-03-17 10:11 UTC, fpistm commented on README.md
> +
Should be in alphabetical order

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F745Z(E-G)Tx_F746Z(E-G)Yx_F746ZETx_F746ZGTx_F750Z8Tx_F756ZG/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
remove the 0.
```suggestion
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {};
```

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F745Z(E-G)Tx_F746Z(E-G)Yx_F746ZETx_F746ZGTx_F750Z8Tx_F756ZG/ldscript.ld
> +
*(.RamFunc)        /* .RamFunc sections */
    *(.RamFunc*)       /* .RamFunc* sections */

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F746B(E-G)Tx_F746NEHx_F746NGHx_F750N8Hx_F756BGTx_F756NGHx/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
```suggestion
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {};
```

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F746B(E-G)Tx_F746NEHx_F746NGHx_F750N8Hx_F756BGTx_F756NGHx/ldscript.ld
> +
*(.RamFunc)        /* .RamFunc sections */
    *(.RamFunc*)       /* .RamFunc* sections */

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F765V(G-I)_F767VG_F767VI_F777VI/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
```suggestion
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {};
```

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F765V(G-I)_F767VG_F767VI_F777VI/ldscript.ld
> +
*(.RamFunc)        /* .RamFunc sections */
    *(.RamFunc*)       /* .RamFunc* sections */

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F765Z(G-I)Tx_F767ZGTx_F767ZITx_F777ZITx/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
```suggestion
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {};
```

2021-03-17 10:11 UTC, fpistm commented on variants/STM32F7xx/F765Z(G-I)Tx_F767ZGTx_F767ZITx_F777ZITx/ldscript.ld
> +
*(.RamFunc)        /* .RamFunc sections */
    *(.RamFunc*)       /* .RamFunc* sections */

2021-03-17 13:24 UTC, ABOSTM commented on README.md
> +
Done

2021-03-17 13:24 UTC, ABOSTM commented on variants/STM32F7xx/F745Z(E-G)Tx_F746Z(E-G)Yx_F746ZETx_F746ZGTx_F750Z8Tx_F756ZG/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
Done

2021-03-17 13:24 UTC, ABOSTM commented on variants/STM32F7xx/F745Z(E-G)Tx_F746Z(E-G)Yx_F746ZETx_F746ZGTx_F750Z8Tx_F756ZG/ldscript.ld
> +
Done

2021-03-17 13:24 UTC, ABOSTM commented on variants/STM32F7xx/F746B(E-G)Tx_F746NEHx_F746NGHx_F750N8Hx_F756BGTx_F756NGHx/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
Done

2021-03-17 13:24 UTC, ABOSTM commented on variants/STM32F7xx/F746B(E-G)Tx_F746NEHx_F746NGHx_F750N8Hx_F756BGTx_F756NGHx/ldscript.ld
> +
Done

2021-03-17 13:24 UTC, ABOSTM commented on variants/STM32F7xx/F765V(G-I)_F767VG_F767VI_F777VI/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
Done

2021-03-17 13:24 UTC, ABOSTM commented on variants/STM32F7xx/F765V(G-I)_F767VG_F767VI_F777VI/ldscript.ld
> +
Done

2021-03-17 13:25 UTC, ABOSTM commented on variants/STM32F7xx/F765Z(G-I)Tx_F767ZGTx_F767ZITx_F777ZITx/generic_clock.c
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
Done

2021-03-17 13:25 UTC, ABOSTM commented on variants/STM32F7xx/F765Z(G-I)Tx_F767ZGTx_F767ZITx_F777ZITx/ldscript.ld
> +
Done

2021-03-17 13:38 UTC, fpistm approved these changes
LGTM. Will integrate to offciial PR
Thanks.

2021-03-22 16:38 UTC, fpistm commented
Integrated to official PR.

Thanks

2021-03-22 16:38 UTC, closed without merging